Recipe App
hamidazim321/recipe_app pull request #23
Opened 2024-02-01 16:50 UTC by hamidazim321

#PR Summary
- We have added the following models and associations
    - `food`
    - `recipe`
    - `user`
    - `food_recipe`
    - `inventory_recipe`
    - `inventory`
- We have added user authentication using `devise` and authorization using `CanCanCan` library
- We have added unit tests and integration tests
- We have added all views according to the wireframe
- We have added controller actions for all required methods `PUT`, `PATCH`, `UPDATE`, `DESTROY`, `GET`
- We have added a shopping list view and a modal for shopping list generator
- We have added all the required associations and the `recipe_food` and `inventory_food` joining tables for the many_to_many relations
- We have added a Navigation bar

2024-02-01 18:29 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️
Hi @hamidazim321, @hydaline-code and @BilalLiaquat7 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHlmcGZ1bGM3cnRmcjJuM3M0cnJlaTlqY2tvaGdrNmcwOGVxaXBsZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/KyBesf8kNT6s88SEgb/200.webp)

## Highlights
:heavy_check_mark: Linters passing
:heavy_check_mark: Correct GitFlow
:heavy_check_mark: All test cases passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-01 18:29 UTC, zeff96 commented on app/views/recipes/public_recipes.html.erb
> +    <%end%>
- [ ] Hey team, fantastic job so far—really impressive! 🚀 However, I've noticed a couple of minor issues that need addressing. According to the project requirements, the public shopping list should exclusively feature recipes from other users, showcasing their names and total prices. In the current implementation, there's a missing element: the total prices for the listed recipes are not being displayed. Let's tweak this to align perfectly with the project specifications! 🛠️👩‍🍳

Project design
![image](https://github.com/hamidazim321/recipe_app/assets/112261237/34ac818c-4ad5-49c5-87e5-e95a8a44846b)

your design
![image](https://github.com/hamidazim321/recipe_app/assets/112261237/8dac263f-6dbe-42a1-b4f7-1bdc99b4b0b7)

Kindly adjust to match the given wireframe

2024-02-01 18:29 UTC, zeff96 commented on app/views/recipes/index.html.erb
> +            <%= button_to "Remove", recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'%>
- [ ] 🔐 According to the project guidelines, only the rightful owner should have the authority to delete a recipe item. It's crucial to enhance security by verifying that the user attempting the deletion is indeed the rightful owner. To achieve this, consider implementing an authorization mechanism, such as CancanCan or any other suitable solution. This mechanism will add an additional layer of protection by ensuring that only users with the appropriate permissions can access the delete functionality. This way, we strengthen the security of our application and guarantee that only authorized individuals can modify or remove recipe items. 🚀

2024-02-01 18:29 UTC, zeff96 commented on app/views/recipes/show.html.erb
> +      <button class="ms-auto" id="food-btn" data-controller="modal" data-modal-id="food-form" data-action="click->modal#controlModal">add food</button>
- [ ] Hello, as per the given wireframe this button should "Add ingredient"

2024-02-01 18:29 UTC, zeff96 commented on app/views/inventories/index.html.erb
> +          <%= button_to "Remove", inventory_path(inventory.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "inventory-card-link inventory-card-link-re
- [ ] 🔐 According to the project guidelines, only the rightful owner should have the authority to delete a inventory item. It's crucial to enhance security by verifying that the user attempting the deletion is indeed the rightful owner. To achieve this, consider implementing an authorization mechanism, such as CancanCan or any other suitable solution. This mechanism will add an additional layer of protection by ensuring that only users with the appropriate permissions can access the delete functionality. This way, we strengthen the security of our application and guarantee that only authorized individuals can modify or remove inventory items. 🚀

2024-02-02 08:08 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @hamidazim321, @hydaline-code, and @BilalLiaquat7👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Good job with model validations. ✔️
- Nice UI design. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-02 08:09 UTC, merged